/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AExprMaxMinExpression extends PExpression
{
    private PMaxMin _maxMin_;
    private TLPar _lPar_;
    private PValue _value_;
    private final LinkedList _groupCommaVal_ = new TypedLinkedList(new GroupCommaVal_Cast());
    private TRPar _rPar_;

    public AExprMaxMinExpression()
    {
    }

    public AExprMaxMinExpression(
        PMaxMin _maxMin_,
        TLPar _lPar_,
        PValue _value_,
        List _groupCommaVal_,
        TRPar _rPar_)
    {
        setMaxMin(_maxMin_);

        setLPar(_lPar_);

        setValue(_value_);

        {
            this._groupCommaVal_.clear();
            this._groupCommaVal_.addAll(_groupCommaVal_);
        }

        setRPar(_rPar_);

    }
    public Object clone()
    {
        return new AExprMaxMinExpression(
            (PMaxMin) cloneNode(_maxMin_),
            (TLPar) cloneNode(_lPar_),
            (PValue) cloneNode(_value_),
            cloneList(_groupCommaVal_),
            (TRPar) cloneNode(_rPar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprMaxMinExpression(this);
    }

    public PMaxMin getMaxMin()
    {
        return _maxMin_;
    }

    public void setMaxMin(PMaxMin node)
    {
        if(_maxMin_ != null)
        {
            _maxMin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _maxMin_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PValue getValue()
    {
        return _value_;
    }

    public void setValue(PValue node)
    {
        if(_value_ != null)
        {
            _value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _value_ = node;
    }

    public LinkedList getGroupCommaVal()
    {
        return _groupCommaVal_;
    }

    public void setGroupCommaVal(List list)
    {
        _groupCommaVal_.clear();
        _groupCommaVal_.addAll(list);
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_maxMin_)
            + toString(_lPar_)
            + toString(_value_)
            + toString(_groupCommaVal_)
            + toString(_rPar_);
    }

    void removeChild(Node child)
    {
        if(_maxMin_ == child)
        {
            _maxMin_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_value_ == child)
        {
            _value_ = null;
            return;
        }

        if(_groupCommaVal_.remove(child))
        {
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_maxMin_ == oldChild)
        {
            setMaxMin((PMaxMin) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator i = _groupCommaVal_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }

    private class GroupCommaVal_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PGroupCommaVal node = (PGroupCommaVal) o;

            if((node.parent() != null) &&
                (node.parent() != AExprMaxMinExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AExprMaxMinExpression.this))
            {
                node.parent(AExprMaxMinExpression.this);
            }

            return node;
        }
    }
}
