/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFromInportImportType extends PImportType
{
    private TFrom _from_;
    private PModule _module_;
    private TImport _import_;
    private TId _id_;
    private PGroupAsId _groupAsId_;
    private final LinkedList _groupCommaId_ = new TypedLinkedList(new GroupCommaId_Cast());

    public AFromInportImportType()
    {
    }

    public AFromInportImportType(
        TFrom _from_,
        PModule _module_,
        TImport _import_,
        TId _id_,
        PGroupAsId _groupAsId_,
        List _groupCommaId_)
    {
        setFrom(_from_);

        setModule(_module_);

        setImport(_import_);

        setId(_id_);

        setGroupAsId(_groupAsId_);

        {
            this._groupCommaId_.clear();
            this._groupCommaId_.addAll(_groupCommaId_);
        }

    }
    public Object clone()
    {
        return new AFromInportImportType(
            (TFrom) cloneNode(_from_),
            (PModule) cloneNode(_module_),
            (TImport) cloneNode(_import_),
            (TId) cloneNode(_id_),
            (PGroupAsId) cloneNode(_groupAsId_),
            cloneList(_groupCommaId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFromInportImportType(this);
    }

    public TFrom getFrom()
    {
        return _from_;
    }

    public void setFrom(TFrom node)
    {
        if(_from_ != null)
        {
            _from_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _from_ = node;
    }

    public PModule getModule()
    {
        return _module_;
    }

    public void setModule(PModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public TImport getImport()
    {
        return _import_;
    }

    public void setImport(TImport node)
    {
        if(_import_ != null)
        {
            _import_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _import_ = node;
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public PGroupAsId getGroupAsId()
    {
        return _groupAsId_;
    }

    public void setGroupAsId(PGroupAsId node)
    {
        if(_groupAsId_ != null)
        {
            _groupAsId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _groupAsId_ = node;
    }

    public LinkedList getGroupCommaId()
    {
        return _groupCommaId_;
    }

    public void setGroupCommaId(List list)
    {
        _groupCommaId_.clear();
        _groupCommaId_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_from_)
            + toString(_module_)
            + toString(_import_)
            + toString(_id_)
            + toString(_groupAsId_)
            + toString(_groupCommaId_);
    }

    void removeChild(Node child)
    {
        if(_from_ == child)
        {
            _from_ = null;
            return;
        }

        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

        if(_import_ == child)
        {
            _import_ = null;
            return;
        }

        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_groupAsId_ == child)
        {
            _groupAsId_ = null;
            return;
        }

        if(_groupCommaId_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_from_ == oldChild)
        {
            setFrom((TFrom) newChild);
            return;
        }

        if(_module_ == oldChild)
        {
            setModule((PModule) newChild);
            return;
        }

        if(_import_ == oldChild)
        {
            setImport((TImport) newChild);
            return;
        }

        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(_groupAsId_ == oldChild)
        {
            setGroupAsId((PGroupAsId) newChild);
            return;
        }

        for(ListIterator i = _groupCommaId_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class GroupCommaId_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PGroupCommaId node = (PGroupCommaId) o;

            if((node.parent() != null) &&
                (node.parent() != AFromInportImportType.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFromInportImportType.this))
            {
                node.parent(AFromInportImportType.this);
            }

            return node;
        }
    }
}
