/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AGroupMod extends PGroupMod
{
    private TComma _comma_;
    private PModule _module_;
    private PGroupAsId _groupAsId_;

    public AGroupMod()
    {
    }

    public AGroupMod(
        TComma _comma_,
        PModule _module_,
        PGroupAsId _groupAsId_)
    {
        setComma(_comma_);

        setModule(_module_);

        setGroupAsId(_groupAsId_);

    }
    public Object clone()
    {
        return new AGroupMod(
            (TComma) cloneNode(_comma_),
            (PModule) cloneNode(_module_),
            (PGroupAsId) cloneNode(_groupAsId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGroupMod(this);
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PModule getModule()
    {
        return _module_;
    }

    public void setModule(PModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public PGroupAsId getGroupAsId()
    {
        return _groupAsId_;
    }

    public void setGroupAsId(PGroupAsId node)
    {
        if(_groupAsId_ != null)
        {
            _groupAsId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _groupAsId_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comma_)
            + toString(_module_)
            + toString(_groupAsId_);
    }

    void removeChild(Node child)
    {
        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

        if(_groupAsId_ == child)
        {
            _groupAsId_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_module_ == oldChild)
        {
            setModule((PModule) newChild);
            return;
        }

        if(_groupAsId_ == oldChild)
        {
            setGroupAsId((PGroupAsId) newChild);
            return;
        }

    }
}
