/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ALessCompTypes extends PCompTypes
{
    private TLess _less_;

    public ALessCompTypes()
    {
    }

    public ALessCompTypes(
        TLess _less_)
    {
        setLess(_less_);

    }
    public Object clone()
    {
        return new ALessCompTypes(
            (TLess) cloneNode(_less_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessCompTypes(this);
    }

    public TLess getLess()
    {
        return _less_;
    }

    public void setLess(TLess node)
    {
        if(_less_ != null)
        {
            _less_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _less_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_less_);
    }

    void removeChild(Node child)
    {
        if(_less_ == child)
        {
            _less_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_less_ == oldChild)
        {
            setLess((TLess) newChild);
            return;
        }

    }
}
