/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AModMathTypes extends PMathTypes
{
    private TPercent _percent_;

    public AModMathTypes()
    {
    }

    public AModMathTypes(
        TPercent _percent_)
    {
        setPercent(_percent_);

    }
    public Object clone()
    {
        return new AModMathTypes(
            (TPercent) cloneNode(_percent_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModMathTypes(this);
    }

    public TPercent getPercent()
    {
        return _percent_;
    }

    public void setPercent(TPercent node)
    {
        if(_percent_ != null)
        {
            _percent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _percent_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_percent_);
    }

    void removeChild(Node child)
    {
        if(_percent_ == child)
        {
            _percent_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_percent_ == oldChild)
        {
            setPercent((TPercent) newChild);
            return;
        }

    }
}
