/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ASimplyImportImportType extends PImportType
{
    private TImport _import_;
    private PModule _module_;
    private PGroupAsId _groupAsId_;
    private final LinkedList _groupMod_ = new TypedLinkedList(new GroupMod_Cast());

    public ASimplyImportImportType()
    {
    }

    public ASimplyImportImportType(
        TImport _import_,
        PModule _module_,
        PGroupAsId _groupAsId_,
        List _groupMod_)
    {
        setImport(_import_);

        setModule(_module_);

        setGroupAsId(_groupAsId_);

        {
            this._groupMod_.clear();
            this._groupMod_.addAll(_groupMod_);
        }

    }
    public Object clone()
    {
        return new ASimplyImportImportType(
            (TImport) cloneNode(_import_),
            (PModule) cloneNode(_module_),
            (PGroupAsId) cloneNode(_groupAsId_),
            cloneList(_groupMod_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplyImportImportType(this);
    }

    public TImport getImport()
    {
        return _import_;
    }

    public void setImport(TImport node)
    {
        if(_import_ != null)
        {
            _import_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _import_ = node;
    }

    public PModule getModule()
    {
        return _module_;
    }

    public void setModule(PModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public PGroupAsId getGroupAsId()
    {
        return _groupAsId_;
    }

    public void setGroupAsId(PGroupAsId node)
    {
        if(_groupAsId_ != null)
        {
            _groupAsId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _groupAsId_ = node;
    }

    public LinkedList getGroupMod()
    {
        return _groupMod_;
    }

    public void setGroupMod(List list)
    {
        _groupMod_.clear();
        _groupMod_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_import_)
            + toString(_module_)
            + toString(_groupAsId_)
            + toString(_groupMod_);
    }

    void removeChild(Node child)
    {
        if(_import_ == child)
        {
            _import_ = null;
            return;
        }

        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

        if(_groupAsId_ == child)
        {
            _groupAsId_ = null;
            return;
        }

        if(_groupMod_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_import_ == oldChild)
        {
            setImport((TImport) newChild);
            return;
        }

        if(_module_ == oldChild)
        {
            setModule((PModule) newChild);
            return;
        }

        if(_groupAsId_ == oldChild)
        {
            setGroupAsId((PGroupAsId) newChild);
            return;
        }

        for(ListIterator i = _groupMod_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class GroupMod_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PGroupMod node = (PGroupMod) o;

            if((node.parent() != null) &&
                (node.parent() != ASimplyImportImportType.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ASimplyImportImportType.this))
            {
                node.parent(ASimplyImportImportType.this);
            }

            return node;
        }
    }
}
