/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ASubAdditionSubition extends PAdditionSubition
{
    private PAdditionSubition _additionSubition_;
    private TMinus _minus_;
    private PMultiplication _multiplication_;

    public ASubAdditionSubition()
    {
    }

    public ASubAdditionSubition(
        PAdditionSubition _additionSubition_,
        TMinus _minus_,
        PMultiplication _multiplication_)
    {
        setAdditionSubition(_additionSubition_);

        setMinus(_minus_);

        setMultiplication(_multiplication_);

    }
    public Object clone()
    {
        return new ASubAdditionSubition(
            (PAdditionSubition) cloneNode(_additionSubition_),
            (TMinus) cloneNode(_minus_),
            (PMultiplication) cloneNode(_multiplication_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubAdditionSubition(this);
    }

    public PAdditionSubition getAdditionSubition()
    {
        return _additionSubition_;
    }

    public void setAdditionSubition(PAdditionSubition node)
    {
        if(_additionSubition_ != null)
        {
            _additionSubition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _additionSubition_ = node;
    }

    public TMinus getMinus()
    {
        return _minus_;
    }

    public void setMinus(TMinus node)
    {
        if(_minus_ != null)
        {
            _minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _minus_ = node;
    }

    public PMultiplication getMultiplication()
    {
        return _multiplication_;
    }

    public void setMultiplication(PMultiplication node)
    {
        if(_multiplication_ != null)
        {
            _multiplication_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multiplication_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_additionSubition_)
            + toString(_minus_)
            + toString(_multiplication_);
    }

    void removeChild(Node child)
    {
        if(_additionSubition_ == child)
        {
            _additionSubition_ = null;
            return;
        }

        if(_minus_ == child)
        {
            _minus_ = null;
            return;
        }

        if(_multiplication_ == child)
        {
            _multiplication_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_additionSubition_ == oldChild)
        {
            setAdditionSubition((PAdditionSubition) newChild);
            return;
        }

        if(_minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(_multiplication_ == oldChild)
        {
            setMultiplication((PMultiplication) newChild);
            return;
        }

    }
}
