/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AExprMaxMinExpression extends PExpression
{
    private PMaxMin _maxMin_;
    private PExpression _expression_;
    private final LinkedList _groupCommaVal_ = new TypedLinkedList(new GroupCommaVal_Cast());

    public AExprMaxMinExpression()
    {
    }

    public AExprMaxMinExpression(
        PMaxMin _maxMin_,
        PExpression _expression_,
        List _groupCommaVal_)
    {
        setMaxMin(_maxMin_);

        setExpression(_expression_);

        {
            this._groupCommaVal_.clear();
            this._groupCommaVal_.addAll(_groupCommaVal_);
        }

    }
    public Object clone()
    {
        return new AExprMaxMinExpression(
            (PMaxMin) cloneNode(_maxMin_),
            (PExpression) cloneNode(_expression_),
            cloneList(_groupCommaVal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprMaxMinExpression(this);
    }

    public PMaxMin getMaxMin()
    {
        return _maxMin_;
    }

    public void setMaxMin(PMaxMin node)
    {
        if(_maxMin_ != null)
        {
            _maxMin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _maxMin_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public LinkedList getGroupCommaVal()
    {
        return _groupCommaVal_;
    }

    public void setGroupCommaVal(List list)
    {
        _groupCommaVal_.clear();
        _groupCommaVal_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_maxMin_)
            + toString(_expression_)
            + toString(_groupCommaVal_);
    }

    void removeChild(Node child)
    {
        if(_maxMin_ == child)
        {
            _maxMin_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_groupCommaVal_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_maxMin_ == oldChild)
        {
            setMaxMin((PMaxMin) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator i = _groupCommaVal_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class GroupCommaVal_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PGroupCommaVal node = (PGroupCommaVal) o;

            if((node.parent() != null) &&
                (node.parent() != AExprMaxMinExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AExprMaxMinExpression.this))
            {
                node.parent(AExprMaxMinExpression.this);
            }

            return node;
        }
    }
}
