/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AGroupCommaIdEqVal extends PGroupCommaIdEqVal
{
    private TId _id_;
    private final LinkedList _groupEqVal_ = new TypedLinkedList(new GroupEqVal_Cast());

    public AGroupCommaIdEqVal()
    {
    }

    public AGroupCommaIdEqVal(
        TId _id_,
        List _groupEqVal_)
    {
        setId(_id_);

        {
            this._groupEqVal_.clear();
            this._groupEqVal_.addAll(_groupEqVal_);
        }

    }
    public Object clone()
    {
        return new AGroupCommaIdEqVal(
            (TId) cloneNode(_id_),
            cloneList(_groupEqVal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGroupCommaIdEqVal(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getGroupEqVal()
    {
        return _groupEqVal_;
    }

    public void setGroupEqVal(List list)
    {
        _groupEqVal_.clear();
        _groupEqVal_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_groupEqVal_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_groupEqVal_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _groupEqVal_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class GroupEqVal_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PGroupEqVal node = (PGroupEqVal) o;

            if((node.parent() != null) &&
                (node.parent() != AGroupCommaIdEqVal.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AGroupCommaIdEqVal.this))
            {
                node.parent(AGroupCommaIdEqVal.this);
            }

            return node;
        }
    }
}
