/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class APercentExpression extends PExpression
{
    private PExpression _multiplication_;
    private PExpression _power_;

    public APercentExpression()
    {
    }

    public APercentExpression(
        PExpression _multiplication_,
        PExpression _power_)
    {
        setMultiplication(_multiplication_);

        setPower(_power_);

    }
    public Object clone()
    {
        return new APercentExpression(
            (PExpression) cloneNode(_multiplication_),
            (PExpression) cloneNode(_power_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPercentExpression(this);
    }

    public PExpression getMultiplication()
    {
        return _multiplication_;
    }

    public void setMultiplication(PExpression node)
    {
        if(_multiplication_ != null)
        {
            _multiplication_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multiplication_ = node;
    }

    public PExpression getPower()
    {
        return _power_;
    }

    public void setPower(PExpression node)
    {
        if(_power_ != null)
        {
            _power_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _power_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_multiplication_)
            + toString(_power_);
    }

    void removeChild(Node child)
    {
        if(_multiplication_ == child)
        {
            _multiplication_ = null;
            return;
        }

        if(_power_ == child)
        {
            _power_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_multiplication_ == oldChild)
        {
            setMultiplication((PExpression) newChild);
            return;
        }

        if(_power_ == oldChild)
        {
            setPower((PExpression) newChild);
            return;
        }

    }
}
