/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ASubExpression extends PExpression
{
    private PExpression _subition_;
    private PExpression _multiplication_;

    public ASubExpression()
    {
    }

    public ASubExpression(
        PExpression _subition_,
        PExpression _multiplication_)
    {
        setSubition(_subition_);

        setMultiplication(_multiplication_);

    }
    public Object clone()
    {
        return new ASubExpression(
            (PExpression) cloneNode(_subition_),
            (PExpression) cloneNode(_multiplication_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubExpression(this);
    }

    public PExpression getSubition()
    {
        return _subition_;
    }

    public void setSubition(PExpression node)
    {
        if(_subition_ != null)
        {
            _subition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _subition_ = node;
    }

    public PExpression getMultiplication()
    {
        return _multiplication_;
    }

    public void setMultiplication(PExpression node)
    {
        if(_multiplication_ != null)
        {
            _multiplication_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multiplication_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_subition_)
            + toString(_multiplication_);
    }

    void removeChild(Node child)
    {
        if(_subition_ == child)
        {
            _subition_ = null;
            return;
        }

        if(_multiplication_ == child)
        {
            _multiplication_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_subition_ == oldChild)
        {
            setSubition((PExpression) newChild);
            return;
        }

        if(_multiplication_ == oldChild)
        {
            setMultiplication((PExpression) newChild);
            return;
        }

    }
}
