/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.lexer;

import java.io.*;
import java.util.*;
import minipython.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;

        if(gotoTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Lexer.class.getResourceAsStream("lexer.dat")));

                // read gotoTable
                int length = s.readInt();
                gotoTable = new int[length][][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][][];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        length = s.readInt();
                        gotoTable[i][j] = new int[length][3];
                        for(int k = 0; k < gotoTable[i][j].length; k++)
                        {
                            for(int l = 0; l < 3; l++)
                            {
                                gotoTable[i][j][k][l] = s.readInt();
                            }
                        }
                    }
                }

                // read accept
                length = s.readInt();
                accept = new int[length][];
                for(int i = 0; i < accept.length; i++)
                {
                    length = s.readInt();
                    accept[i] = new int[length];
                    for(int j = 0; j < accept[i].length; j++)
                    {
                        accept[i][j] = s.readInt();
                    }
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
            }
        }
    }

    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            Token token = new47(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            Token token = new50(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            Token token = new51(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(int line, int pos) { return new TImport(line, pos); }
    Token new1(int line, int pos) { return new TDef(line, pos); }
    Token new2(int line, int pos) { return new TLPar(line, pos); }
    Token new3(int line, int pos) { return new TRPar(line, pos); }
    Token new4(int line, int pos) { return new TSemi(line, pos); }
    Token new5(int line, int pos) { return new TAs(line, pos); }
    Token new6(int line, int pos) { return new TEq(line, pos); }
    Token new7(int line, int pos) { return new TComma(line, pos); }
    Token new8(String text, int line, int pos) { return new TTab(text, line, pos); }
    Token new9(int line, int pos) { return new TIf(line, pos); }
    Token new10(int line, int pos) { return new TWhile(line, pos); }
    Token new11(int line, int pos) { return new TFor(line, pos); }
    Token new12(int line, int pos) { return new TIn(line, pos); }
    Token new13(int line, int pos) { return new TReturn(line, pos); }
    Token new14(int line, int pos) { return new TPrint(line, pos); }
    Token new15(int line, int pos) { return new TMinusEq(line, pos); }
    Token new16(int line, int pos) { return new TDivEq(line, pos); }
    Token new17(int line, int pos) { return new TLBr(line, pos); }
    Token new18(int line, int pos) { return new TRBr(line, pos); }
    Token new19(int line, int pos) { return new TAssert(line, pos); }
    Token new20(int line, int pos) { return new TPlus(line, pos); }
    Token new21(int line, int pos) { return new TMinus(line, pos); }
    Token new22(int line, int pos) { return new TMult(line, pos); }
    Token new23(int line, int pos) { return new TDmult(line, pos); }
    Token new24(int line, int pos) { return new TDiv(line, pos); }
    Token new25(int line, int pos) { return new TPercent(line, pos); }
    Token new26(int line, int pos) { return new TExclam(line, pos); }
    Token new27(int line, int pos) { return new TDict(line, pos); }
    Token new28(int line, int pos) { return new TLogicPlus(line, pos); }
    Token new29(int line, int pos) { return new TMax(line, pos); }
    Token new30(int line, int pos) { return new TMin(line, pos); }
    Token new31(int line, int pos) { return new TAnd(line, pos); }
    Token new32(int line, int pos) { return new TOr(line, pos); }
    Token new33(int line, int pos) { return new TNot(line, pos); }
    Token new34(int line, int pos) { return new TLess(line, pos); }
    Token new35(int line, int pos) { return new TGreat(line, pos); }
    Token new36(int line, int pos) { return new TGreatEq(line, pos); }
    Token new37(int line, int pos) { return new TLessEq(line, pos); }
    Token new38(int line, int pos) { return new TNotEq(line, pos); }
    Token new39(int line, int pos) { return new TEqual(line, pos); }
    Token new40(int line, int pos) { return new TTrue(line, pos); }
    Token new41(int line, int pos) { return new TFalse(line, pos); }
    Token new42(int line, int pos) { return new TQuote(line, pos); }
    Token new43(int line, int pos) { return new TLen(line, pos); }
    Token new44(int line, int pos) { return new TFrom(line, pos); }
    Token new45(int line, int pos) { return new TDot(line, pos); }
    Token new46(int line, int pos) { return new TNone(line, pos); }
    Token new47(String text, int line, int pos) { return new TLineComment(text, line, pos); }
    Token new48(String text, int line, int pos) { return new TNumber(text, line, pos); }
    Token new49(String text, int line, int pos) { return new TId(text, line, pos); }
    Token new50(String text, int line, int pos) { return new TString(text, line, pos); }
    Token new51(String text, int line, int pos) { return new TBlank(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {35, 35, 7}, {37, 37, 8}, {38, 38, 9}, {39, 39, 10}, {40, 40, 11}, {41, 41, 12}, {42, 42, 13}, {43, 43, 14}, {44, 44, 15}, {45, 45, 16}, {46, 46, 17}, {47, 47, 18}, {48, 57, 19}, {58, 58, 20}, {60, 60, 21}, {61, 61, 22}, {62, 62, 23}, {65, 77, 24}, {78, 78, 25}, {79, 90, 24}, {91, 91, 26}, {93, 93, 27}, {97, 97, 28}, {98, 99, 29}, {100, 100, 30}, {101, 101, 29}, {102, 102, 31}, {103, 104, 29}, {105, 105, 32}, {106, 107, 29}, {108, 108, 33}, {109, 109, 34}, {110, 110, 35}, {111, 111, 36}, {112, 112, 37}, {113, 113, 29}, {114, 114, 38}, {115, 115, 29}, {116, 116, 39}, {117, 118, 29}, {119, 119, 40}, {120, 122, 29}, },
            {},
            {},
            {},
            {},
            {{61, 61, 41}, },
            {{0, 9, 42}, {11, 12, 42}, {14, 33, 42}, {34, 34, 43}, {35, 127, 42}, },
            {{0, 9, 44}, {10, 10, 45}, {11, 12, 44}, {13, 13, 46}, {14, 127, 44}, },
            {},
            {{38, 38, 47}, },
            {{0, 9, 48}, {11, 12, 48}, {14, 38, 48}, {39, 39, 49}, {40, 127, 48}, },
            {},
            {},
            {{42, 42, 50}, },
            {},
            {},
            {{61, 61, 51}, },
            {},
            {{61, 61, 52}, },
            {{46, 46, 53}, {48, 57, 19}, },
            {},
            {{61, 61, 54}, },
            {{61, 61, 55}, },
            {{61, 61, 56}, },
            {{48, 57, 57}, {65, 90, 58}, {97, 122, 59}, },
            {{48, 90, -26}, {97, 110, 59}, {111, 111, 60}, {112, 122, 59}, },
            {},
            {},
            {{48, 90, -26}, {97, 109, 59}, {110, 110, 61}, {111, 114, 59}, {115, 115, 62}, {116, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 90, -26}, {97, 100, 59}, {101, 101, 63}, {102, 104, 59}, {105, 105, 64}, {106, 122, 59}, },
            {{48, 90, -26}, {97, 97, 65}, {98, 110, 59}, {111, 111, 66}, {112, 113, 59}, {114, 114, 67}, {115, 122, 59}, },
            {{48, 90, -26}, {97, 101, 59}, {102, 102, 68}, {103, 108, 59}, {109, 109, 69}, {110, 110, 70}, {111, 122, 59}, },
            {{48, 100, -32}, {101, 101, 71}, {102, 122, 59}, },
            {{48, 90, -26}, {97, 97, 72}, {98, 104, 59}, {105, 105, 73}, {106, 122, 59}, },
            {{48, 110, -27}, {111, 111, 74}, {112, 122, 59}, },
            {{48, 90, -26}, {97, 113, 59}, {114, 114, 75}, {115, 122, 59}, },
            {{48, 113, -38}, {114, 114, 76}, {115, 122, 59}, },
            {{48, 100, -32}, {101, 101, 77}, {102, 122, 59}, },
            {{48, 113, -38}, {114, 114, 78}, {115, 122, 59}, },
            {{48, 90, -26}, {97, 103, 59}, {104, 104, 79}, {105, 122, 59}, },
            {},
            {{0, 127, -8}, },
            {{0, 127, -8}, },
            {{0, 127, -9}, },
            {},
            {{10, 10, 80}, },
            {},
            {{0, 127, -12}, },
            {{0, 127, -12}, },
            {},
            {},
            {},
            {{48, 57, 81}, },
            {},
            {},
            {},
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 109, -30}, {110, 110, 82}, {111, 122, 59}, },
            {{48, 90, -26}, {97, 99, 59}, {100, 100, 83}, {101, 122, 59}, },
            {{48, 90, -26}, {97, 114, 59}, {115, 115, 84}, {116, 122, 59}, },
            {{48, 101, -34}, {102, 102, 85}, {103, 122, 59}, },
            {{48, 90, -26}, {97, 98, 59}, {99, 99, 86}, {100, 122, 59}, },
            {{48, 90, -26}, {97, 107, 59}, {108, 108, 87}, {109, 122, 59}, },
            {{48, 113, -38}, {114, 114, 88}, {115, 122, 59}, },
            {{48, 110, -27}, {111, 111, 89}, {112, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 90, -26}, {97, 111, 59}, {112, 112, 90}, {113, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 109, -30}, {110, 110, 91}, {111, 122, 59}, },
            {{48, 90, -26}, {97, 119, 59}, {120, 120, 92}, {121, 122, 59}, },
            {{48, 109, -30}, {110, 110, 93}, {111, 122, 59}, },
            {{48, 90, -26}, {97, 115, 59}, {116, 116, 94}, {117, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 90, -26}, {97, 104, 59}, {105, 105, 95}, {106, 122, 59}, },
            {{48, 115, -76}, {116, 116, 96}, {117, 122, 59}, },
            {{48, 90, -26}, {97, 116, 59}, {117, 117, 97}, {118, 122, 59}, },
            {{48, 104, -78}, {105, 105, 98}, {106, 122, 59}, },
            {},
            {{48, 57, 81}, },
            {{48, 100, -32}, {101, 101, 99}, {102, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 100, -32}, {101, 101, 100}, {102, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 115, -76}, {116, 116, 101}, {117, 122, 59}, },
            {{48, 114, -64}, {115, 115, 102}, {116, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 90, -26}, {97, 108, 59}, {109, 109, 103}, {110, 122, 59}, },
            {{48, 110, -27}, {111, 111, 104}, {112, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 109, -30}, {110, 110, 105}, {111, 122, 59}, },
            {{48, 116, -80}, {117, 117, 106}, {118, 122, 59}, },
            {{48, 100, -32}, {101, 101, 107}, {102, 122, 59}, },
            {{48, 107, -67}, {108, 108, 108}, {109, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 113, -38}, {114, 114, 109}, {115, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 100, -32}, {101, 101, 110}, {102, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 113, -38}, {114, 114, 111}, {115, 122, 59}, },
            {{48, 115, -76}, {116, 116, 112}, {117, 122, 59}, },
            {{48, 113, -38}, {114, 114, 113}, {115, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 100, -32}, {101, 101, 114}, {102, 122, 59}, },
            {{48, 115, -76}, {116, 116, 115}, {117, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 115, -76}, {116, 116, 116}, {117, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 109, -30}, {110, 110, 117}, {111, 122, 59}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 8, 51, 51, 51, 26, 42, -1, 25, -1, -1, 2, 3, 22, 20, 7, 21, 45, 24, 48, 4, 34, 6, 35, 49, 49, 17, 18, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 38, -1, 50, -1, 47, 47, 28, -1, 50, 23, 15, 16, -1, 37, 39, 36, 49, 49, 49, 49, 49, 5, 49, 49, 49, 49, 49, 9, 49, 12, 49, 49, 49, 49, 32, 49, 49, 49, 49, 47, 48, 49, 31, 49, 1, 49, 49, 11, 49, 49, 43, 29, 30, 33, 49, 49, 49, 49, 46, 49, 27, 49, 44, 49, 49, 49, 40, 49, 49, 41, 49, 14, 49, 10, 19, 0, 13, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }
}
