/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.node.*;
import minipython.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTImport(TImport node)
    {
        index = 0;
    }

    public void caseTDef(TDef node)
    {
        index = 1;
    }

    public void caseTLPar(TLPar node)
    {
        index = 2;
    }

    public void caseTRPar(TRPar node)
    {
        index = 3;
    }

    public void caseTSemi(TSemi node)
    {
        index = 4;
    }

    public void caseTAs(TAs node)
    {
        index = 5;
    }

    public void caseTEq(TEq node)
    {
        index = 6;
    }

    public void caseTComma(TComma node)
    {
        index = 7;
    }

    public void caseTTab(TTab node)
    {
        index = 8;
    }

    public void caseTIf(TIf node)
    {
        index = 9;
    }

    public void caseTWhile(TWhile node)
    {
        index = 10;
    }

    public void caseTFor(TFor node)
    {
        index = 11;
    }

    public void caseTIn(TIn node)
    {
        index = 12;
    }

    public void caseTReturn(TReturn node)
    {
        index = 13;
    }

    public void caseTPrint(TPrint node)
    {
        index = 14;
    }

    public void caseTMinusEq(TMinusEq node)
    {
        index = 15;
    }

    public void caseTDivEq(TDivEq node)
    {
        index = 16;
    }

    public void caseTLBr(TLBr node)
    {
        index = 17;
    }

    public void caseTRBr(TRBr node)
    {
        index = 18;
    }

    public void caseTAssert(TAssert node)
    {
        index = 19;
    }

    public void caseTPlus(TPlus node)
    {
        index = 20;
    }

    public void caseTMinus(TMinus node)
    {
        index = 21;
    }

    public void caseTMult(TMult node)
    {
        index = 22;
    }

    public void caseTDmult(TDmult node)
    {
        index = 23;
    }

    public void caseTDiv(TDiv node)
    {
        index = 24;
    }

    public void caseTPercent(TPercent node)
    {
        index = 25;
    }

    public void caseTExclam(TExclam node)
    {
        index = 26;
    }

    public void caseTDict(TDict node)
    {
        index = 27;
    }

    public void caseTLogicPlus(TLogicPlus node)
    {
        index = 28;
    }

    public void caseTMax(TMax node)
    {
        index = 29;
    }

    public void caseTMin(TMin node)
    {
        index = 30;
    }

    public void caseTAnd(TAnd node)
    {
        index = 31;
    }

    public void caseTOr(TOr node)
    {
        index = 32;
    }

    public void caseTNot(TNot node)
    {
        index = 33;
    }

    public void caseTLess(TLess node)
    {
        index = 34;
    }

    public void caseTGreat(TGreat node)
    {
        index = 35;
    }

    public void caseTGreatEq(TGreatEq node)
    {
        index = 36;
    }

    public void caseTLessEq(TLessEq node)
    {
        index = 37;
    }

    public void caseTNotEq(TNotEq node)
    {
        index = 38;
    }

    public void caseTEqual(TEqual node)
    {
        index = 39;
    }

    public void caseTTrue(TTrue node)
    {
        index = 40;
    }

    public void caseTFalse(TFalse node)
    {
        index = 41;
    }

    public void caseTQuote(TQuote node)
    {
        index = 42;
    }

    public void caseTLen(TLen node)
    {
        index = 43;
    }

    public void caseTFrom(TFrom node)
    {
        index = 44;
    }

    public void caseTDot(TDot node)
    {
        index = 45;
    }

    public void caseTNone(TNone node)
    {
        index = 46;
    }

    public void caseTNumber(TNumber node)
    {
        index = 47;
    }

    public void caseTId(TId node)
    {
        index = 48;
    }

    public void caseTString(TString node)
    {
        index = 49;
    }

    public void caseEOF(EOF node)
    {
        index = 50;
    }
}
